name: solar_icon_pack
description: "Flutter package that provides Solar icons which is 7,500+ icons in 6 different styles."

version: 0.1.0

icon: assets/logo.png
homepage: https://softyes.com.br

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  very_good_analysis: ^6.0.0
